export const ALL_BRAND_REQUEST = 'ALL_BRAND_REQUEST';
export const ALL_BRAND_SUCCESS = 'ALL_BRAND_SUCCESS';
export const ALL_BRAND_FAILED = 'ALL_BRAND_FAILED';

export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
