export const ALL_CATEGORY_REQUEST = 'ALL_CATEGORY_REQUEST';
export const ALL_CATEGORY_SUCCESS = 'ALL_CATEGORY_SUCCESS';
export const ALL_CATEGORY_FAILED = 'ALL_CATEGORY_FAILED';

export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
