export const ALL_COLOR_REQUEST = 'ALL_COLOR_REQUEST';
export const ALL_COLOR_SUCCESS = 'ALL_COLOR_SUCCESS';
export const ALL_COLOR_FAILED = 'ALL_COLOR_FAILED';

export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
